[package]
name = "zettelkasten"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.34", features = ["derive"] }
colored = "3.0.0"

[[bin]]
name = "zet"
path = "src/main.rs"
